<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vortex.Shared\Vortex.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vortex.Modules.Behaviour.Abstraction\Vortex.Modules.Behaviour.Abstraction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Player.Abstraction\Vortex.Modules.Player.Abstraction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Entities.Abstraction\Vortex.Modules.Entities.Abstraction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Inventory.Abstraction\Vortex.Modules.Inventory.Abstraction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Interaction.Abstraction\Vortex.Modules.Interaction.Abstraction.csproj" />
  </ItemGroup>

</Project>
