<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../ProjectConfiguration.Base.csproj" />
    <Import Project="../ProjectConfiguration.Module.csproj" />
    <ItemGroup>
      <ProjectReference Include="..\Vortex.Modules.World.Abstraction\Vortex.Modules.World.Abstraction.csproj" />
    </ItemGroup>
    <ItemGroup>
      <InternalsVisibleTo Include="Vortex.Modules.World.Test" />
    </ItemGroup>

</Project>
