<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.1" />
    <PackageReference Include="Serilog.Extensions.Autofac.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Vortex.Framework.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vortex.Framework.Abstraction\Vortex.Framework.Abstraction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Behaviour\Vortex.Modules.Behaviour.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Chat\Vortex.Modules.Chat.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Navigation\Vortex.Modules.Navigation.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Networking\Vortex.Modules.Networking.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Player\Vortex.Modules.Player.csproj" />
    <ProjectReference Include="..\Vortex.Modules.World\Vortex.Modules.World.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Entities\Vortex.Modules.Entities.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Inventory\Vortex.Modules.Inventory.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Interaction\Vortex.Modules.Interaction.csproj" />
    <ProjectReference Include="..\Vortex.Modules.Crafting\Vortex.Modules.Crafting.csproj" />
  </ItemGroup>

</Project>
