<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../ProjectConfiguration.Base.csproj" />

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Vortex.Modules.Navigation.Abstraction\Vortex.Modules.Navigation.Abstraction.csproj" />
        <ProjectReference Include="..\Vortex.Modules.World.Abstraction\Vortex.Modules.World.Abstraction.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Vortex.Modules.Navigation.Test" />
    </ItemGroup>

</Project>
