using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Vortex.Modules.Networking.CodeGeneration;

/// <summary>
/// Generates the packet IDs of the protocol from Mojang's own packet report,
/// so they never have to be looked up and typed by hand.
/// </summary>
/// <remarks>
/// The report is produced by the vanilla server's data generator, see
/// scripts/update-protocol-data.sh. Regenerating it is what a version bump
/// mostly consists of.
/// </remarks>
[Generator]
public class PacketIdGenerator : ISourceGenerator
{
    /// <summary>
    /// The assembly the IDs are generated into. The generator runs in every module
    /// that references it, but the constants must exist exactly once.
    /// </summary>
    private const string TargetAssemblyName = "Vortex.Modules.Networking.Abstraction";

    private const string ResourceName = "Vortex.Modules.Networking.CodeGeneration.Resources.packets.json";

    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.Compilation.AssemblyName != TargetAssemblyName)
            return;

        var report = ReadReport();
        if (report is null)
            return;

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {TargetAssemblyName};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Packet IDs of the protocol, generated from Mojang's packet report.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static class PacketIds");
        builder.AppendLine("{");

        foreach (var state in report.OrderBy(s => s.Key, StringComparer.Ordinal))
        {
            if (state.Value is not JsonObject directions)
                continue;

            builder.AppendLine($"    public static class {ToPascalCase(state.Key)}");
            builder.AppendLine("    {");

            foreach (var direction in directions.OrderBy(d => d.Key, StringComparer.Ordinal))
            {
                if (direction.Value is not JsonObject packets)
                    continue;

                builder.AppendLine($"        public static class {ToDirectionName(direction.Key)}");
                builder.AppendLine("        {");

                foreach (var packet in packets.OrderBy(p => p.Key, StringComparer.Ordinal))
                {
                    if (packet.Value is not JsonObject definition)
                        continue;

                    var id = definition.GetInt("protocol_id");
                    if (id is null)
                        continue;

                    builder.AppendLine($"            /// <summary>{packet.Key}</summary>");
                    builder.AppendLine($"            public const int {ToPascalCase(StripNamespace(packet.Key))} = 0x{id.Value:X2};");
                }

                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");

        context.AddSource("PacketIds.g.cs", builder.ToString());
    }

    private static JsonObject? ReadReport()
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName);

        if (stream is null)
            return null;

        using var reader = new StreamReader(stream);

        return SimpleJson.Parse(reader.ReadToEnd());
    }

    /// <summary>
    /// Matches the spelling of <c>PacketDirection</c> instead of the report's lowercase form.
    /// </summary>
    private static string ToDirectionName(string direction)
        => direction switch
        {
            "clientbound" => "ClientBound",
            "serverbound" => "ServerBound",
            _ => ToPascalCase(direction)
        };

    private static string StripNamespace(string name)
    {
        var separator = name.IndexOf(':');

        return separator < 0 ? name : name.Substring(separator + 1);
    }

    private static string ToPascalCase(string name)
        => string.Concat(name
            .Replace('/', '_')
            .Replace('.', '_')
            .Split(new[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(word => char.ToUpperInvariant(word[0]) + word.Substring(1).ToLowerInvariant()));
}
